
Module1_Question=['I can\'t find my keys. I don\'t know where ____ are.','Is he a teacher?" B: "Yes, he _."',' "_____ brush your teeth?" B: "Three times a day."','We _ have friends over for dinner.','That\'s _. It\'s very expensive.','_ summer, I get up early _ Sunday mornings.','Please, can you stop making noise? I _ a book.','When _?','Does he have _?','What _ tomorrow?']
Module1_Answer=[['it','them','they','they'],['is','\'s','does','is'],['How often do you','When you','How often are you','How often do you'],['often don\'t','don\'t often','don\'t never','often don\'t'],['Anna\'s car','the car of Anna','Anna car','Anna\'s car'],['In/in','At/on','In/on','In/on'],['I\'m reading','read','reading','I\'m reading'],['they arrived','did they arrived','did they arrive','did they arrive'],['any sisters','any sister','some sisters','any sisters'],['will you do','do you do','are you going to do','will you do']]
Module2_Question=['_ sugar do you want in your tea?','Peter is _ player in the team.','I sat _ on the couch and watched a documentary. ', 'I got up and had _ breakfast very quickly because I was late.' ,'_ any water in the fridge?','_____ did you live in New York?" B: "I lived there for almost five years.','When ____?','They threw a rock _ the window and broke the glass.',"'He didn/'t speak English', '_ it was difficult to make him understand what he had to do.",'Why did you turn off the TV?" B: "Because I _. I\'m very tired.']
Module2_Answer=[['How much','How many','What','How much'],['the stronger','the strongest','the most strong','the strongest'],['comfortable','quiet','comfortably','comfortably'],['_','the','a','_'],['Is there','There is','a','Is there'],['When','How much','How long','When'],['did you arrived','did you arrive','were you arrived','did you arrive'],['through','across','into','into'],['although','because','so','so'],['go to sleep','will go to sleep',"'m going to sleep","'m going to sleep"]]
Module3_Question=['_ sugar do you want in your tea?','Peter is _ player in the team.','I sat _ on the couch and watched a documentary. ', 'I got up and had _ breakfast very quickly because I was late.' ,'_ any water in the fridge?','_____ did you live in New York?" B: "I lived there for almost five years.','When ____?','They threw a rock _ the window and broke the glass.',"'He didn/'t speak English', '_ it was difficult to make him understand what he had to do.",'Why did you turn off the TV?" B: "Because I _. I\'m very tired.']
Module3_Answer=[['How much','How many','What','How much'],['the stronger','the strongest','the most strong','the strongest'],['comfortable','quiet','comfortably','comfortably'],['_','the','a','_'],['Is there','There is','a','Is there'],['When','How much','How long','When'],['did you arrived','did you arrive','were you arrived','did you arrive'],['through','across','into','into'],['although','because','so','so'],['go to sleep','will go to sleep',"'m going to sleep","'m going to sleep"]]
Module4_Question=['_ sugar do you want in your tea?','Peter is _ player in the team.','I sat _ on the couch and watched a documentary. ', 'I got up and had _ breakfast very quickly because I was late.' ,'_ any water in the fridge?','_____ did you live in New York?" B: "I lived there for almost five years.','When ____?','They threw a rock _ the window and broke the glass.',"'He didn/'t speak English', '_ it was difficult to make him understand what he had to do.",'Why did you turn off the TV?" B: "Because I _. I\'m very tired.']
Module4_Answer=[['How much','How many','What','How much'],['the stronger','the strongest','the most strong','the strongest'],['comfortable','quiet','comfortably','comfortably'],['_','the','a','_'],['Is there','There is','a','Is there'],['When','How much','How long','When'],['did you arrived','did you arrive','were you arrived','did you arrive'],['through','across','into','into'],['although','because','so','so'],['go to sleep','will go to sleep',"'m going to sleep","'m going to sleep"]]
Module5_Question=['_ sugar do you want in your tea?','Peter is _ player in the team.','I sat _ on the couch and watched a documentary. ', 'I got up and had _ breakfast very quickly because I was late.' ,'_ any water in the fridge?','_____ did you live in New York?" B: "I lived there for almost five years.','When ____?','They threw a rock _ the window and broke the glass.',"'He didn/'t speak English', '_ it was difficult to make him understand what he had to do.",'Why did you turn off the TV?" B: "Because I _. I\'m very tired.']
Module5_Answer=[['How much','How many','What','How much'],['the stronger','the strongest','the most strong','the strongest'],['comfortable','quiet','comfortably','comfortably'],['_','the','a','_'],['Is there','There is','a','Is there'],['When','How much','How long','When'],['did you arrived','did you arrive','were you arrived','did you arrive'],['through','across','into','into'],['although','because','so','so'],['go to sleep','will go to sleep',"'m going to sleep","'m going to sleep"]]
Module6_Question=['_ sugar do you want in your tea?','Peter is _ player in the team.','I sat _ on the couch and watched a documentary. ', 'I got up and had _ breakfast very quickly because I was late.' ,'_ any water in the fridge?','_____ did you live in New York?" B: "I lived there for almost five years.','When ____?','They threw a rock _ the window and broke the glass.',"'He didn/'t speak English', '_ it was difficult to make him understand what he had to do.",'Why did you turn off the TV?" B: "Because I _. I\'m very tired.']
Module6_Answer=[['How much','How many','What','How much'],['the stronger','the strongest','the most strong','the strongest'],['comfortable','quiet','comfortably','comfortably'],['_','the','a','_'],['Is there','There is','a','Is there'],['When','How much','How long','When'],['did you arrived','did you arrive','were you arrived','did you arrive'],['through','across','into','into'],['although','because','so','so'],['go to sleep','will go to sleep',"'m going to sleep","'m going to sleep"]]

Congratulations=['Great, Bro','You`r God damn right','Perfectly answer','It`s amazing','You`r God']
Fails=['You can be better','Sorry , but no', 'This test was failed','Okay, but no']

Past_Simple_All_Questions_and_Answers={'Module1':[Module1_Question,Module1_Answer],'Module2':[Module2_Question,Module2_Answer], 'Module3':[Module3_Question,Module3_Answer],
                           'Module4':[Module4_Question,Module4_Answer],'Module5':[Module5_Question,Module5_Answer], 'Module6':[Module6_Question,Module6_Answer],}


Name_of_main=['Времена', 'Артикли', 'Conditional','Information about us']
Name_of_modules=['Module1', 'Module2', 'Module3','Module4','Module5','Module6']
Name_of_categories= {'Present Simple', 'Past Simple', 'Future Simple', 'Traveling', 'Sport', 'Information about us'}
